# Generated by Django 4.1.7 on 2023-04-09 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalOperationsAlias",
            fields=[],
            options={
                "verbose_name": "Fiscal Operation Alias",
                "verbose_name_plural": "Fiscal Operations Alias",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.ledger_fiscal_operations",),
        ),
        migrations.CreateModel(
            name="ShopAlias",
            fields=[],
            options={
                "verbose_name": "Shop Alias",
                "verbose_name_plural": "Shops Alias",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.ledger_shop",),
        ),
        migrations.AlterField(
            model_name="ledger_category",
            name="id",
            field=models.AutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ledger_category",
            name="name",
            field=models.TextField(db_column="name", max_length=4000),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="created_at",
            field=models.DateTimeField(
                db_column="created_at",
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="date",
            field=models.DateTimeField(
                db_column="date", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="id",
            field=models.AutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="rrn",
            field=models.IntegerField(db_column="rrn", unique=True),
        ),
        migrations.AlterField(
            model_name="ledger_shop",
            name="id",
            field=models.AutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ledger_shop",
            name="name",
            field=models.TextField(db_column="name", max_length=4000),
        ),
    ]
