# Generated by Django 4.1.7 on 2023-04-09 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_ledger_category_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ledger_category",
            table="ledger_category",
        ),
        migrations.AlterModelTable(
            name="ledger_fiscal_operations",
            table="ledger_fiscal_operations",
        ),
        migrations.AlterModelTable(
            name="ledger_shop",
            table="ledger_shop",
        ),
    ]
