# Generated by Django 4.1.7 on 2023-04-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_ledger_category_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger_category",
            name="created_at",
            field=models.DateField(db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="ledger_category",
            name="id",
            field=models.AutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ledger_category",
            name="name",
            field=models.TextField(db_column="name"),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="amt",
            field=models.DecimalField(
                db_column="amt", decimal_places=2, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="created_at",
            field=models.DateField(db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="id",
            field=models.AutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="rrn",
            field=models.IntegerField(db_column="rrn", unique=True),
        ),
        migrations.AlterField(
            model_name="ledger_operation_type",
            name="created_at",
            field=models.DateField(db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="ledger_operation_type",
            name="id",
            field=models.AutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ledger_operation_type",
            name="name",
            field=models.TextField(db_column="name"),
        ),
        migrations.AlterField(
            model_name="ledger_shop",
            name="category_id",
            field=models.ForeignKey(
                db_column="category_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ledger_category",
            ),
        ),
        migrations.AlterField(
            model_name="ledger_shop",
            name="created_at",
            field=models.DateField(db_column="created_at"),
        ),
        migrations.AlterField(
            model_name="ledger_shop",
            name="id",
            field=models.AutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ledger_shop",
            name="name",
            field=models.TextField(db_column="name"),
        ),
    ]
