# Generated by Django 4.1.7 on 2023-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_ledger_category_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="date",
            field=models.DateField(db_column="date"),
        ),
    ]
