# Generated by Django 4.1.7 on 2023-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_ledger_fiscal_operations_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fiscaloperationsalias",
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
            },
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="date",
            field=models.DateField(auto_now_add=True, db_column="date"),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="rrn",
            field=models.BigIntegerField(
                db_column="rrn", default=None, unique=True
            ),
        ),
    ]
