# Generated by Django 4.1.7 on 2023-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_ledger_fiscal_operations_operation_type_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="date",
            field=models.DateField(db_column="date"),
        ),
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="rrn",
            field=models.BigIntegerField(db_column="rrn", unique=True),
        ),
    ]
