# Generated by Django 4.1.7 on 2023-04-20 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_delete_fiscaloperationsalias"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopAlias",
        ),
        migrations.AlterModelOptions(
            name="ledger_fiscal_operations",
            options={"ordering": ["-created_at"]},
        ),
    ]
