# Generated by Django 4.1.7 on 2023-04-20 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_delete_shopalias_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledger_fiscal_operations",
            options={},
        ),
    ]
