# Generated by Django 4.1.7 on 2023-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_ledger_fiscal_operations_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger_fiscal_operations",
            name="rrn",
            field=models.BigIntegerField(
                blank=True, db_column="rrn", null=True, unique=True
            ),
        ),
    ]
